### ISSUE TITLE
Да просто поблагодарить хотел

### ISSUE THREAD

**Issue by DarkSeasonStudios** [shubin/q3c#14]
Крутейший проект, ребяты! Сейчас на кармане дыра, но как появится чего-нить обязательно задоначу. Заодно оповестите общественность - чем можем помочь вещественно, иконки, модельки, карты, ... ? Есть ли возможность поучаствовать в разработке желающим? И чем именно, помимо кода? (на плюсах не умею). В любом случае - удачи и спасибо!

**Comment by shubin** [comment]
Привет, спасибо!
Предлагаю переместиться для более детального общения в более подходящее место, напиши пожалуйста мне на почту svshubin@ гмайл ком
